In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('./data/test.csv',index_col=0)

In [3]:
df2 = pd.read_csv('./data/train.csv',index_col=0)

In [4]:
df = pd.concat([df1,df2])

In [5]:
df.set_index('id',inplace=True)

In [6]:
df.reset_index('id',inplace=True)

In [7]:
df = df.drop('id',axis=1)

In [8]:
df.dropna(inplace=True)

In [9]:
df.shape[0]

129487

In [12]:
df.columns

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [30]:
df

성별              고객 유형  나이            비행 목적       클래스  비행 거리  \
0       Female     Loyal Customer  52  Business travel       Eco    160   
1       Female     Loyal Customer  36  Business travel  Business   2863   
2         Male  disloyal Customer  20  Business travel       Eco    192   
3         Male     Loyal Customer  44  Business travel  Business   3377   
4       Female     Loyal Customer  49  Business travel       Eco   1182   
...        ...                ...  ..              ...       ...    ...   
129875  Female  disloyal Customer  23  Business travel       Eco    192   
129876    Male     Loyal Customer  49  Business travel  Business   2347   
129877    Male  disloyal Customer  30  Business travel  Business   1995   
129878  Female  disloyal Customer  22  Business travel       Eco   1000   
129879    Male     Loyal Customer  27  Business travel  Business   1723   

        기내 와이파이 서비스  출발/도착 시간 편의성  온라인 예약 편의성  탑승구 위치  ...  기내 엔터테인먼트  탑승 서비스  \
0                 5             4           3       4  ...          5       5   
1                 1             1           3       1  ...          4       4   
2                 2             0           2       4  ...          2       4   
3                 0             0           0       2  ...          1       1   
4                 2             3           4       3  ...          2       2   
...             ...           ...         ...     ...  ...        ...     ...   
129875            2             1           2       3  ...          2       3   
129876            4             4           4       4  ...          5       5   
129877            1             1           1       3  ...          4       3   
129878            1             1           1       5  ...          1       4   
129879            1             3           3       3  ...          1       1   

        다리 공간 서비스  수하물 처리  체크인 서비스  기내 서비스  청결도  출발 지연(분)  도착 지연(분)  \
0               5       5        2       5    5        50      44.0   
1               4       4        3       4    5         0       0.0   
2               1       3        2       2    2         0       0.0   
3               1       1        3       1    4         0       6.0   
4               2       2        4       2    4         0      20.0   
...           ...     ...      ...     ...  ...       ...       ...   
129875          1       4        2       3    2         3       0.0   
129876          5       5        5       5    4         0       0.0   
129877          2       4        5       5    4         7      14.0   
129878          5       1        5       4    1         0       0.0   
129879          1       4        4       3    1         0       0.0   

                            만족도  
0                     satisfied  
1                     satisfied  
2       neutral or dissatisfied  
3                     satisfied  
4                     satisfied  
...                         ...  
129875  neutral or dissatisfied  
129876                satisfied  
129877  neutral or dissatisfied  
129878  neutral or dissatisfied  
129879  neutral or dissatisfied  

[129487 rows x 23 columns]

In [13]:
translation = {
    'Gender': '성별',
    'Customer Type': '고객 유형',
    'Age': '나이',
    'Type of Travel': '비행 목적',
    'Class': '클래스',
    'Flight Distance': '비행 거리',
    'Inflight wifi service': '기내 와이파이 서비스',
    'Departure/Arrival time convenient': '출발/도착 시간 편의성',
    'Ease of Online booking': '온라인 예약 편의성',
    'Gate location': '탑승구 위치',
    'Food and drink': '음식과 음료',
    'Online boarding': '온라인 탑승',
    'Seat comfort': '좌석 편안함',
    'Inflight entertainment': '기내 엔터테인먼트',
    'On-board service': '탑승 서비스',
    'Leg room service': '다리 공간 서비스',
    'Baggage handling': '수하물 처리',
    'Checkin service': '체크인 서비스',
    'Inflight service': '기내 서비스',
    'Cleanliness': '청결도',
    'Departure Delay in Minutes': '출발 지연(분)',
    'Arrival Delay in Minutes': '도착 지연(분)',
    'satisfaction': '만족도'
}
df.columns = [translation[col] for col in df.columns]

In [108]:
df
df.to_csv('./data/Airline_sa.csv')

In [20]:
pd.get_dummies(df['고객 유형'].to_frame())

고객 유형_Loyal Customer  고객 유형_disloyal Customer
0                       True                    False
1                       True                    False
2                      False                     True
3                       True                    False
4                       True                    False
...                      ...                      ...
129875                 False                     True
129876                  True                    False
129877                 False                     True
129878                 False                     True
129879                  True                    False

[129487 rows x 2 columns]

In [32]:
df.loc[  : , '기내 와이파이 서비스':'청결도' ]

기내 와이파이 서비스  출발/도착 시간 편의성  온라인 예약 편의성  탑승구 위치  음식과 음료  온라인 탑승  좌석 편안함  \
0                 5             4           3       4       3       4       3   
1                 1             1           3       1       5       4       5   
2                 2             0           2       4       2       2       2   
3                 0             0           0       2       3       4       4   
4                 2             3           4       3       4       1       2   
...             ...           ...         ...     ...     ...     ...     ...   
129875            2             1           2       3       2       2       2   
129876            4             4           4       4       2       4       5   
129877            1             1           1       3       4       1       5   
129878            1             1           1       5       1       1       1   
129879            1             3           3       3       1       1       1   

        기내 엔터테인먼트  탑승 서비스  다리 공간 서비스  수하물 처리  체크인 서비스  기내 서비스  청결도  
0               5       5          5       5        2       5    5  
1               4       4          4       4        3       4    5  
2               2       4          1       3        2       2    2  
3               1       1          1       1        3       1    4  
4               2       2          2       2        4       2    4  
...           ...     ...        ...     ...      ...     ...  ...  
129875          2       3          1       4        2       3    2  
129876          5       5          5       5        5       5    4  
129877          4       3          2       4        5       5    4  
129878          1       4          5       1        5       4    1  
129879          1       1          1       4        4       3    1  

[129487 rows x 14 columns]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [17]:
df['성별'].dtypes == object

True

In [42]:
df['만족도'].replace({'satisfied' : 1 , 'neutral or dissatisfied' : 0} )

0         1
1         1
2         0
3         1
4         1
         ..
129875    0
129876    1
129877    0
129878    0
129879    0
Name: 만족도, Length: 129487, dtype: int64

In [160]:
df['성별'].unique()

array(['Female', 'Male'], dtype=object)

In [110]:
X = df.iloc[ : , 0: -1 ]

In [111]:
y = df['만족도']

In [18]:
X

NameError: name 'X' is not defined

In [113]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [114]:
encoder = LabelEncoder()

In [115]:
sorted(X['성별'].unique())

['Female', 'Male']

In [116]:
X['성별'] = encoder.fit_transform(X['성별'])

In [117]:
sorted(X['고객 유형'].unique())

['Loyal Customer', 'disloyal Customer']

In [118]:
X['고객 유형'] = encoder.fit_transform(X['고객 유형'])

In [119]:
sorted(X['비행 목적'].unique())

['Business travel', 'Personal Travel']

In [120]:
X['비행 목적'] = encoder.fit_transform(X['비행 목적'])

In [121]:
sorted(X['클래스'].unique())

['Business', 'Eco', 'Eco Plus']

In [122]:
ct = ColumnTransformer([ ('encoder', OneHotEncoder(),[4]) ] , remainder = 'passthrough')

In [123]:
X = ct.fit_transform( X )

In [194]:
X

array([[0.        , 1.        , 0.        , ..., 1.        , 0.03140704,
        0.02777778],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.4       , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.8       , 0.00439698,
        0.00883838],
       [0.        , 1.        , 0.        , ..., 0.2       , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.2       , 0.        ,
        0.        ]])

In [195]:
sorted(y.unique())

AttributeError: 'numpy.ndarray' object has no attribute 'unique'

In [126]:
y = encoder.fit_transform(y)

In [127]:
y

array([1, 1, 0, ..., 0, 0, 0])

In [128]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [129]:
X_scaler = MinMaxScaler()

In [130]:
X = X_scaler.fit_transform(X)

In [131]:
X

array([[0.        , 1.        , 0.        , ..., 1.        , 0.03140704,
        0.02777778],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.4       , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.8       , 0.00439698,
        0.00883838],
       [0.        , 1.        , 0.        , ..., 0.2       , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.2       , 0.        ,
        0.        ]])

In [132]:
from sklearn.model_selection import train_test_split

In [133]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [134]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [135]:
from sklearn.tree import DecisionTreeClassifier

In [136]:
classifier = DecisionTreeClassifier(random_state=1)

In [137]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier(random_state=1)

In [138]:
y_pred = classifier.predict(X_test)

In [139]:
accuracy_score(y_test,y_pred)

0.9466368059309599

In [140]:
confusion_matrix(y_test,y_pred)

array([[13815,   722],
       [  660, 10701]], dtype=int64)

In [141]:
import joblib

In [142]:
joblib.dump(classifier,'classifier.pkl')

['classifier.pkl']

In [143]:
joblib.dump(ct,'ct.pkl')

['ct.pkl']