In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('./data/test.csv',index_col=0)

In [3]:
df2 = pd.read_csv('./data/train.csv',index_col=0)

In [4]:
df = pd.concat([df1,df2])

In [5]:
df.set_index('id',inplace=True)

In [6]:
df.reset_index('id',inplace=True)

In [7]:
df = df.drop('id',axis=1)

In [8]:
df.dropna(inplace=True)

In [59]:
df.to_csv('./data/Airline_sa.csv')

In [10]:
df.columns

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [11]:
X = df.iloc[ : , 0: -1 ]

In [12]:
y = df['satisfaction']

In [13]:
X

Gender      Customer Type  Age   Type of Travel     Class  \
0       Female     Loyal Customer   52  Business travel       Eco   
1       Female     Loyal Customer   36  Business travel  Business   
2         Male  disloyal Customer   20  Business travel       Eco   
3         Male     Loyal Customer   44  Business travel  Business   
4       Female     Loyal Customer   49  Business travel       Eco   
...        ...                ...  ...              ...       ...   
129875  Female  disloyal Customer   23  Business travel       Eco   
129876    Male     Loyal Customer   49  Business travel  Business   
129877    Male  disloyal Customer   30  Business travel  Business   
129878  Female  disloyal Customer   22  Business travel       Eco   
129879    Male     Loyal Customer   27  Business travel  Business   

        Flight Distance  Inflight wifi service  \
0                   160                      5   
1                  2863                      1   
2                   192                      2   
3                  3377                      0   
4                  1182                      2   
...                 ...                    ...   
129875              192                      2   
129876             2347                      4   
129877             1995                      1   
129878             1000                      1   
129879             1723                      1   

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3   
1                                       1                       3   
2                                       0                       2   
3                                       0                       0   
4                                       3                       4   
...                                   ...                     ...   
129875                                  1                       2   
129876                                  4                       4   
129877                                  1                       1   
129878                                  1                       1   
129879                                  3                       3   

        Gate location  ...  Seat comfort  Inflight entertainment  \
0                   4  ...             3                       5   
1                   1  ...             5                       4   
2                   4  ...             2                       2   
3                   2  ...             4                       1   
4                   3  ...             2                       2   
...               ...  ...           ...                     ...   
129875              3  ...             2                       2   
129876              4  ...             5                       5   
129877              3  ...             5                       4   
129878              5  ...             1                       1   
129879              3  ...             1                       1   

        On-board service  Leg room service  Baggage handling  Checkin service  \
0                      5                 5                 5                2   
1                      4                 4                 4                3   
2                      4                 1                 3                2   
3                      1                 1                 1                3   
4                      2                 2                 2                4   
...                  ...               ...               ...              ...   
129875                 3                 1                 4                2   
129876                 5                 5                 5                5   
129877                 3                 2                 4                5   
129878                 4                 5                 1                5   
129879                 1                 

In [14]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [15]:
encoder = LabelEncoder()

In [16]:
sorted(X['Gender'].unique())

['Female', 'Male']

In [17]:
X['Gender'] = encoder.fit_transform(X['Gender'])

In [18]:
sorted(X['Customer Type'].unique())

['Loyal Customer', 'disloyal Customer']

In [19]:
X['Customer Type'] = encoder.fit_transform(X['Customer Type'])

In [20]:
sorted(X['Type of Travel'].unique())

['Business travel', 'Personal Travel']

In [21]:
X['Type of Travel'] = encoder.fit_transform(X['Type of Travel'])

In [22]:
sorted(X['Class'].unique())

['Business', 'Eco', 'Eco Plus']

In [23]:
ct = ColumnTransformer([ ('encoder', OneHotEncoder(),[4]) ] , remainder = 'passthrough')

In [24]:
X = ct.fit_transform( X )

In [25]:
X

array([[ 0.,  1.,  0., ...,  5., 50., 44.],
       [ 1.,  0.,  0., ...,  5.,  0.,  0.],
       [ 0.,  1.,  0., ...,  2.,  0.,  0.],
       ...,
       [ 1.,  0.,  0., ...,  4.,  7., 14.],
       [ 0.,  1.,  0., ...,  1.,  0.,  0.],
       [ 1.,  0.,  0., ...,  1.,  0.,  0.]])

In [26]:
sorted(y.unique())

['neutral or dissatisfied', 'satisfied']

In [27]:
y = encoder.fit_transform(y)

In [28]:
y

array([1, 1, 0, ..., 0, 0, 0])

In [29]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [30]:
X_scaler = MinMaxScaler()

In [31]:
X = X_scaler.fit_transform(X)

In [32]:
X

array([[0.        , 1.        , 0.        , ..., 1.        , 0.03140704,
        0.02777778],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.4       , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.8       , 0.00439698,
        0.00883838],
       [0.        , 1.        , 0.        , ..., 0.2       , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.2       , 0.        ,
        0.        ]])

In [33]:
from sklearn.model_selection import train_test_split

In [34]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [41]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [35]:
from sklearn.tree import DecisionTreeClassifier

In [51]:
classifier = DecisionTreeClassifier(random_state=1)

In [52]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier(random_state=1)

In [53]:
y_pred = classifier.predict(X_test)

In [54]:
accuracy_score(y_test,y_pred)

0.9466368059309599

In [55]:
confusion_matrix(y_test,y_pred)

array([[13815,   722],
       [  660, 10701]], dtype=int64)

In [60]:
import joblib

In [61]:
joblib.dump(classifier,'classifier.pkl')

['classifier.pkl']

In [62]:
joblib.dump(ct,'ct.pkl')

['ct.pkl']