In [357]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [358]:
df1 = pd.read_csv('./data/test.csv',index_col=0)

In [359]:
df2 = pd.read_csv('./data/train.csv',index_col=0)

In [360]:
df = pd.concat([df1,df2])

In [361]:
df.set_index('id',inplace=True)

In [362]:
df.reset_index('id',inplace=True)

In [363]:
df = df.drop('id',axis=1)

In [364]:
df.dropna(inplace=True)

In [365]:
df.shape[0]

129487

In [366]:
df.columns

Index(['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class',
       'Flight Distance', 'Inflight wifi service',
       'Departure/Arrival time convenient', 'Ease of Online booking',
       'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort',
       'Inflight entertainment', 'On-board service', 'Leg room service',
       'Baggage handling', 'Checkin service', 'Inflight service',
       'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes',
       'satisfaction'],
      dtype='object')

In [367]:
df

Gender      Customer Type  Age   Type of Travel     Class  \
0       Female     Loyal Customer   52  Business travel       Eco   
1       Female     Loyal Customer   36  Business travel  Business   
2         Male  disloyal Customer   20  Business travel       Eco   
3         Male     Loyal Customer   44  Business travel  Business   
4       Female     Loyal Customer   49  Business travel       Eco   
...        ...                ...  ...              ...       ...   
129875  Female  disloyal Customer   23  Business travel       Eco   
129876    Male     Loyal Customer   49  Business travel  Business   
129877    Male  disloyal Customer   30  Business travel  Business   
129878  Female  disloyal Customer   22  Business travel       Eco   
129879    Male     Loyal Customer   27  Business travel  Business   

        Flight Distance  Inflight wifi service  \
0                   160                      5   
1                  2863                      1   
2                   192                      2   
3                  3377                      0   
4                  1182                      2   
...                 ...                    ...   
129875              192                      2   
129876             2347                      4   
129877             1995                      1   
129878             1000                      1   
129879             1723                      1   

        Departure/Arrival time convenient  Ease of Online booking  \
0                                       4                       3   
1                                       1                       3   
2                                       0                       2   
3                                       0                       0   
4                                       3                       4   
...                                   ...                     ...   
129875                                  1                       2   
129876                                  4                       4   
129877                                  1                       1   
129878                                  1                       1   
129879                                  3                       3   

        Gate location  ...  Inflight entertainment  On-board service  \
0                   4  ...                       5                 5   
1                   1  ...                       4                 4   
2                   4  ...                       2                 4   
3                   2  ...                       1                 1   
4                   3  ...                       2                 2   
...               ...  ...                     ...               ...   
129875              3  ...                       2                 3   
129876              4  ...                       5                 5   
129877              3  ...                       4                 3   
129878              5  ...                       1                 4   
129879              3  ...                       1                 1   

        Leg room service  Baggage handling  Checkin service  Inflight service  \
0                      5                 5                2                 5   
1                      4                 4                3                 4   
2                      1                 3                2                 2   
3                      1                 1                3                 1   
4                      2                 2                4                 2   
...                  ...               ...              ...               ...   
129875                 1                 4                2                 3   
129876                 5                 5                5                 5   
129877                 2                 4                5                 5   
129878                 5                 1                5               

In [368]:
translation = {
    'Gender': '성별',
    'Customer Type': '고객 유형',
    'Age': '나이',
    'Type of Travel': '비행 목적',
    'Class': '클래스',
    'Flight Distance': '비행 거리',
    'Inflight wifi service': '기내 와이파이 서비스',
    'Departure/Arrival time convenient': '출발/도착 시간 편의성',
    'Ease of Online booking': '온라인 예약 편의성',
    'Gate location': '탑승구 위치',
    'Food and drink': '음식과 음료',
    'Online boarding': '온라인 탑승',
    'Seat comfort': '좌석 편안함',
    'Inflight entertainment': '기내 엔터테인먼트',
    'On-board service': '탑승 서비스',
    'Leg room service': '다리 공간 서비스',
    'Baggage handling': '수하물 처리',
    'Checkin service': '체크인 서비스',
    'Inflight service': '기내 서비스',
    'Cleanliness': '청결도',
    'Departure Delay in Minutes': '출발 지연(분)',
    'Arrival Delay in Minutes': '도착 지연(분)',
    'satisfaction': '만족도'
}
df.columns = [translation[col] for col in df.columns]

In [369]:
df
df.to_csv('./data/Airline_sa.csv')

In [370]:
pd.get_dummies(df['고객 유형'].to_frame())

고객 유형_Loyal Customer  고객 유형_disloyal Customer
0                       True                    False
1                       True                    False
2                      False                     True
3                       True                    False
4                       True                    False
...                      ...                      ...
129875                 False                     True
129876                  True                    False
129877                 False                     True
129878                 False                     True
129879                  True                    False

[129487 rows x 2 columns]

In [371]:
df3 = df.loc[  : , '기내 와이파이 서비스':'청결도' ]

In [372]:
df4 = df.drop(labels='만족도',axis=1)

In [373]:
df4 = df4.drop(labels=df4.loc[  : , '기내 와이파이 서비스':'청결도' ],axis=1)

In [374]:
df4['온라인 탑승'] = df['온라인 탑승']

In [375]:
df4['좌석 편안함'] = df['좌석 편안함']

In [376]:
df4['기내 엔터테인먼트'] = df['기내 엔터테인먼트']

In [377]:
df4['탑승 서비스'] = df['탑승 서비스']

In [378]:
df4['다리 공간 서비스'] = df['다리 공간 서비스']

In [379]:
df4['만족도'] = df['만족도']

In [380]:
df4.to_csv('df4.csv')

In [381]:
df4.drop(labels='만족도',axis=1,inplace=True)

In [382]:
df4

성별              고객 유형  나이            비행 목적       클래스  비행 거리  \
0       Female     Loyal Customer  52  Business travel       Eco    160   
1       Female     Loyal Customer  36  Business travel  Business   2863   
2         Male  disloyal Customer  20  Business travel       Eco    192   
3         Male     Loyal Customer  44  Business travel  Business   3377   
4       Female     Loyal Customer  49  Business travel       Eco   1182   
...        ...                ...  ..              ...       ...    ...   
129875  Female  disloyal Customer  23  Business travel       Eco    192   
129876    Male     Loyal Customer  49  Business travel  Business   2347   
129877    Male  disloyal Customer  30  Business travel  Business   1995   
129878  Female  disloyal Customer  22  Business travel       Eco   1000   
129879    Male     Loyal Customer  27  Business travel  Business   1723   

        출발 지연(분)  도착 지연(분)  온라인 탑승  좌석 편안함  기내 엔터테인먼트  탑승 서비스  다리 공간 서비스  
0             50      44.0       4       3          5       5          5  
1              0       0.0       4       5          4       4          4  
2              0       0.0       2       2          2       4          1  
3              0       6.0       4       4          1       1          1  
4              0      20.0       1       2          2       2          2  
...          ...       ...     ...     ...        ...     ...        ...  
129875         3       0.0       2       2          2       3          1  
129876         0       0.0       4       5          5       5          5  
129877         7      14.0       1       5          4       3          2  
129878         0       0.0       1       1          1       4          5  
129879         0       0.0       1       1          1       1          1  

[129487 rows x 13 columns]

In [383]:
df3['기내 와이파이 서비스'].value_counts().index > 3 

array([False, False,  True, False,  True, False])

In [384]:
df.iloc[ : ,  :-1 ].columns

Index(['성별', '고객 유형', '나이', '비행 목적', '클래스', '비행 거리', '기내 와이파이 서비스',
       '출발/도착 시간 편의성', '온라인 예약 편의성', '탑승구 위치', '음식과 음료', '온라인 탑승', '좌석 편안함',
       '기내 엔터테인먼트', '탑승 서비스', '다리 공간 서비스', '수하물 처리', '체크인 서비스', '기내 서비스',
       '청결도', '출발 지연(분)', '도착 지연(분)'],
      dtype='object')

In [385]:
df['성별'].dtypes == object

True

In [386]:
df['만족도'].replace({'satisfied' : 1 , 'neutral or dissatisfied' : 0} )

0         1
1         1
2         0
3         1
4         1
         ..
129875    0
129876    1
129877    0
129878    0
129879    0
Name: 만족도, Length: 129487, dtype: int64

In [387]:
df['성별'].unique()

array(['Female', 'Male'], dtype=object)

In [388]:
X = df.iloc[ : , 0: -1 ]

In [389]:
y = df['만족도']

In [390]:
X

성별              고객 유형  나이            비행 목적       클래스  비행 거리  \
0       Female     Loyal Customer  52  Business travel       Eco    160   
1       Female     Loyal Customer  36  Business travel  Business   2863   
2         Male  disloyal Customer  20  Business travel       Eco    192   
3         Male     Loyal Customer  44  Business travel  Business   3377   
4       Female     Loyal Customer  49  Business travel       Eco   1182   
...        ...                ...  ..              ...       ...    ...   
129875  Female  disloyal Customer  23  Business travel       Eco    192   
129876    Male     Loyal Customer  49  Business travel  Business   2347   
129877    Male  disloyal Customer  30  Business travel  Business   1995   
129878  Female  disloyal Customer  22  Business travel       Eco   1000   
129879    Male     Loyal Customer  27  Business travel  Business   1723   

        기내 와이파이 서비스  출발/도착 시간 편의성  온라인 예약 편의성  탑승구 위치  ...  좌석 편안함  기내 엔터테인먼트  \
0                 5             4           3       4  ...       3          5   
1                 1             1           3       1  ...       5          4   
2                 2             0           2       4  ...       2          2   
3                 0             0           0       2  ...       4          1   
4                 2             3           4       3  ...       2          2   
...             ...           ...         ...     ...  ...     ...        ...   
129875            2             1           2       3  ...       2          2   
129876            4             4           4       4  ...       5          5   
129877            1             1           1       3  ...       5          4   
129878            1             1           1       5  ...       1          1   
129879            1             3           3       3  ...       1          1   

        탑승 서비스  다리 공간 서비스  수하물 처리  체크인 서비스  기내 서비스  청결도  출발 지연(분)  도착 지연(분)  
0            5          5       5        2       5    5        50      44.0  
1            4          4       4        3       4    5         0       0.0  
2            4          1       3        2       2    2         0       0.0  
3            1          1       1        3       1    4         0       6.0  
4            2          2       2        4       2    4         0      20.0  
...        ...        ...     ...      ...     ...  ...       ...       ...  
129875       3          1       4        2       3    2         3       0.0  
129876       5          5       5        5       5    4         0       0.0  
129877       3          2       4        5       5    4         7      14.0  
129878       4          5       1        5       4    1         0       0.0  
129879       1          1       4        4       3    1         0       0.0  

[129487 rows x 22 columns]

In [391]:
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [392]:
encoder = LabelEncoder()

In [393]:
sorted(X['성별'].unique())

['Female', 'Male']

In [394]:
X['성별'] = encoder.fit_transform(X['성별'])

In [395]:
sorted(X['고객 유형'].unique())

['Loyal Customer', 'disloyal Customer']

In [396]:
X['고객 유형'] = encoder.fit_transform(X['고객 유형'])

In [397]:
sorted(X['비행 목적'].unique())

['Business travel', 'Personal Travel']

In [398]:
X['비행 목적'] = encoder.fit_transform(X['비행 목적'])

In [399]:
sorted(X['클래스'].unique())

['Business', 'Eco', 'Eco Plus']

In [400]:
ct = ColumnTransformer([ ('encoder', OneHotEncoder(),[4]) ] , remainder = 'passthrough')

In [401]:
X = ct.fit_transform( X )

In [402]:
X

array([[ 0.,  1.,  0., ...,  5., 50., 44.],
       [ 1.,  0.,  0., ...,  5.,  0.,  0.],
       [ 0.,  1.,  0., ...,  2.,  0.,  0.],
       ...,
       [ 1.,  0.,  0., ...,  4.,  7., 14.],
       [ 0.,  1.,  0., ...,  1.,  0.,  0.],
       [ 1.,  0.,  0., ...,  1.,  0.,  0.]])

In [403]:
sorted(y.unique())

['neutral or dissatisfied', 'satisfied']

In [404]:
y = encoder.fit_transform(y)

In [405]:
y

array([1, 1, 0, ..., 0, 0, 0])

In [406]:
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [407]:
X_scaler = MinMaxScaler()

In [408]:
X = X_scaler.fit_transform(X)

In [409]:
X

array([[0.        , 1.        , 0.        , ..., 1.        , 0.03140704,
        0.02777778],
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.4       , 0.        ,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 0.8       , 0.00439698,
        0.00883838],
       [0.        , 1.        , 0.        , ..., 0.2       , 0.        ,
        0.        ],
       [1.        , 0.        , 0.        , ..., 0.2       , 0.        ,
        0.        ]])

In [410]:
from sklearn.model_selection import train_test_split

In [411]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)

In [412]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [413]:
from sklearn.tree import DecisionTreeClassifier

In [414]:
classifier = DecisionTreeClassifier(random_state=1)

In [415]:
classifier.fit(X_train,y_train)

DecisionTreeClassifier(random_state=1)

In [416]:
y_pred = classifier.predict(X_test)

In [417]:
accuracy_score(y_test,y_pred)

0.9466368059309599

In [418]:
confusion_matrix(y_test,y_pred)

array([[13815,   722],
       [  660, 10701]], dtype=int64)

In [419]:
import joblib

In [420]:
joblib.dump(classifier,'classifier.pkl')

['classifier.pkl']

In [421]:
joblib.dump(ct,'ct.pkl')

['ct.pkl']

In [422]:
df4

성별              고객 유형  나이            비행 목적       클래스  비행 거리  \
0       Female     Loyal Customer  52  Business travel       Eco    160   
1       Female     Loyal Customer  36  Business travel  Business   2863   
2         Male  disloyal Customer  20  Business travel       Eco    192   
3         Male     Loyal Customer  44  Business travel  Business   3377   
4       Female     Loyal Customer  49  Business travel       Eco   1182   
...        ...                ...  ..              ...       ...    ...   
129875  Female  disloyal Customer  23  Business travel       Eco    192   
129876    Male     Loyal Customer  49  Business travel  Business   2347   
129877    Male  disloyal Customer  30  Business travel  Business   1995   
129878  Female  disloyal Customer  22  Business travel       Eco   1000   
129879    Male     Loyal Customer  27  Business travel  Business   1723   

        출발 지연(분)  도착 지연(분)  온라인 탑승  좌석 편안함  기내 엔터테인먼트  탑승 서비스  다리 공간 서비스  
0             50      44.0       4       3          5       5          5  
1              0       0.0       4       5          4       4          4  
2              0       0.0       2       2          2       4          1  
3              0       6.0       4       4          1       1          1  
4              0      20.0       1       2          2       2          2  
...          ...       ...     ...     ...        ...     ...        ...  
129875         3       0.0       2       2          2       3          1  
129876         0       0.0       4       5          5       5          5  
129877         7      14.0       1       5          4       3          2  
129878         0       0.0       1       1          1       4          5  
129879         0       0.0       1       1          1       1          1  

[129487 rows x 13 columns]

In [423]:
# df4 를 가공해보자! => df4는 상관관계가 큰 것들만 골라 가공 후 머신러닝을 만들 예정

In [424]:
X1 = df4
X1['성별']

0         Female
1         Female
2           Male
3           Male
4         Female
           ...  
129875    Female
129876      Male
129877      Male
129878    Female
129879      Male
Name: 성별, Length: 129487, dtype: object

In [425]:
X1['성별'] =encoder.fit_transform(X1['성별'])

In [426]:
X1['고객 유형'] = encoder.fit_transform(X1['고객 유형'])

In [427]:
X1['비행 목적'] = encoder.fit_transform(X1['비행 목적'])

In [428]:
X1

성별  고객 유형  나이  비행 목적       클래스  비행 거리  출발 지연(분)  도착 지연(분)  온라인 탑승  \
0        0      0  52      0       Eco    160        50      44.0       4   
1        0      0  36      0  Business   2863         0       0.0       4   
2        1      1  20      0       Eco    192         0       0.0       2   
3        1      0  44      0  Business   3377         0       6.0       4   
4        0      0  49      0       Eco   1182         0      20.0       1   
...     ..    ...  ..    ...       ...    ...       ...       ...     ...   
129875   0      1  23      0       Eco    192         3       0.0       2   
129876   1      0  49      0  Business   2347         0       0.0       4   
129877   1      1  30      0  Business   1995         7      14.0       1   
129878   0      1  22      0       Eco   1000         0       0.0       1   
129879   1      0  27      0  Business   1723         0       0.0       1   

        좌석 편안함  기내 엔터테인먼트  탑승 서비스  다리 공간 서비스  
0            3          5       5          5  
1            5          4       4          4  
2            2          2       4          1  
3            4          1       1          1  
4            2          2       2          2  
...        ...        ...     ...        ...  
129875       2          2       3          1  
129876       5          5       5          5  
129877       5          4       3          2  
129878       1          1       4          5  
129879       1          1       1          1  

[129487 rows x 13 columns]

In [429]:
ct2 = ColumnTransformer([ ('encoder', OneHotEncoder(),[4]) ] , remainder = 'passthrough')

In [430]:
X1 = ct2.fit_transform(X1)

In [431]:
X1

array([[0., 1., 0., ..., 5., 5., 5.],
       [1., 0., 0., ..., 4., 4., 4.],
       [0., 1., 0., ..., 2., 4., 1.],
       ...,
       [1., 0., 0., ..., 4., 3., 2.],
       [0., 1., 0., ..., 1., 4., 5.],
       [1., 0., 0., ..., 1., 1., 1.]])

In [432]:
X1

array([[0., 1., 0., ..., 5., 5., 5.],
       [1., 0., 0., ..., 4., 4., 4.],
       [0., 1., 0., ..., 2., 4., 1.],
       ...,
       [1., 0., 0., ..., 4., 3., 2.],
       [0., 1., 0., ..., 1., 4., 5.],
       [1., 0., 0., ..., 1., 1., 1.]])

In [433]:
X_train2,X_test2,y_train2,y_test2 = train_test_split(X,y,test_size=0.2,random_state=10)

In [434]:
X_train2

array([[1.        , 0.        , 0.        , ..., 0.2       , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 1.        , 0.01256281,
        0.00315657],
       [0.        , 1.        , 0.        , ..., 0.4       , 0.00942211,
        0.        ],
       ...,
       [1.        , 0.        , 0.        , ..., 1.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.        , ..., 0.6       , 0.        ,
        0.00631313],
       [0.        , 1.        , 0.        , ..., 0.8       , 0.        ,
        0.00757576]])

In [435]:
classifier2 = DecisionTreeClassifier(random_state=1)

In [436]:
classifier2.fit(X_train2,y_train2)

DecisionTreeClassifier(random_state=1)

In [437]:
y_pred2 = classifier2.predict(X_test2)

In [438]:
accuracy_score(y_pred2,y_test2)

0.9466368059309599

In [439]:
joblib.dump(ct2,'ct2.pkl')

['ct2.pkl']

In [440]:
joblib.dump(classifier2,'classifier2.pkl')

['classifier2.pkl']